### PR TITLE
solve some build problems, add a dsp wrapper for espeak

### PR DESCRIPTION
**Pull request by gefin**
Navit did not  build because a old patch dont match.
Some direkt soureforge links failed.
espeak dont work direct on TT
glib1 used gcc instead of arm-linux-gcc

### CODE REVIEW

**Comment by jandegr** [comment]
Hi,
I have been working on building Navit with cmake because autotools is not supported in Navit anymore and if you want a complete Navit build using autotools you will have to maintain it all on your own.

https://github.com/jandegr/navit/blob/tomtom/ci/build_tomtom.sh

I used the espeak wrapper as well as it was posted on the Navit forum, just modified the paths because I am building a packaged to drop in an existing tomtom sd card as described here
http://wiki.navit-project.org/index.php/TomTom.

working fine on a tomtom go 710

**Comment by gefin** [comment]
Hi,

nice to hear.
I use a TT XL and a TT730. The XL has the better Display but only 32M 
RAM. Because of this using navit in the tomtom environment is no option.

I tried cmake in the opentom environment, but had problems with the 
search path while cross compiling.

Gettext dont work with opentom. At the moment i translate navigation.c 
manual.

Gernot

**Comment by jandegr** [comment]
If you pull the navit source from github instead of sourceforge you will notice navigation goes a lot faster.

feel free to comment on https://github.com/navit-gps/navit/pull/119 as well.

If you then use cmake as well you will notice translations working fine without workarounds and you can tweak tomtom.xslt to your needs instead of forking navit.xml, for now just if you pull the tomtom2 branch untill it gets merged.

**Comment by george-hopkins** [comment]
I'm sorry it took so long to review your changes. I finally revived my TomTom device and the build process now works way better than before.

Thank you very much for your contribution!

**Pull request merged**
