### PR TITLE
update navit to git R6816

### PR DESCRIPTION
**Pull request by gefin**
This version routes faster.
I xhanged also the git call for microwin and nxlib because debian 7 dont understand -C.

### CODE REVIEW

**Comment by george-hopkins** [comment]
Thank you again for your fixes! I just pushed all changes to the `next` branch. In theory, telnet, SSH, tuxchess and Navit should work on this branch. You can find a precompiled image [here](https://59-39123037-gh.circle-artifacts.com/0/home/ubuntu/opentom/target/opentom-extra.tar.gz).

Unfortunately, I can't access my own TomTom device to test it, so your help in testing would be very appreciated :wink:

**Comment by gefin** [comment]
Thanks. Most things work well.
The posted archive is 2 times gziped

Bluetooth serial console work well.

Blootooth PPP need additional pppd . Also  the kernelmodule ppp_async is not loaded automatic. I send more information the next days. My device TT730 has no working usb gadget driver so i can test dropbear tomorrow.

tuxchess work

Navit work and speak only US language. I have a Script for "comile time" translation. Don`t got intl to work. I make some tests with cmake...

**Comment by gefin** [comment]
The smallest working version who compile without errors was 2.4.5. Stripped size is 240000 Bytes
 https://download.samba.org/pub/ppp/ppp-2.4.5.tar.gz

should we add it (only pppd)?

**Comment by george-hopkins** [comment]
Thanks again for your fixes and your tests. :+1: All your changes are now part of the `main` branch (cherry-picked).

As for `pppd`: I created a separate issue #15 to determine inclusion.

**Pull request closed without merging**
